### ISSUE TITLE
Not work for me

### ISSUE THREAD

**Issue by aderbas** [wearefractal/status#1]
I'm using Ubuntu 14.04, Node 6.9.4. I installed using -g, installed successfully but it does not work. I already tried using root.

`$ status os uptime`

```
/usr/lib/node_modules/status/node_modules/loggo/lib/package.coffee:14
        if (!this["package"] && path.existsSync(place)) {
                                     ^

TypeError: path.existsSync is not a function
    at Object.exports.load (/usr/lib/node_modules/status/node_modules/loggo/lib/package.coffee:8:95)
    at Object.<anonymous> (/usr/lib/node_modules/status/node_modules/loggo/lib/logger.coffee:3:29)
    at Object.<anonymous> (/usr/lib/node_modules/status/node_modules/loggo/lib/logger.coffee:1:1)
    at Module._compile (module.js:570:32)
    at Object.loadFile (/usr/lib/node_modules/status/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/usr/lib/node_modules/status/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/status/node_modules/loggo/index.js:2:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (/usr/lib/node_modules/status/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/status/lib/command.coffee:2:7)
    at Object.<anonymous> (/usr/lib/node_modules/status/lib/command.coffee:1:1)
    at Module._compile (module.js:570:32)
    at Object.loadFile (/usr/lib/node_modules/status/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/usr/lib/node_modules/status/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/status/bin/status:4:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

```

**Comment by yocontra** [comment]
Yeah this library is pretty old and needs some updates most likely - that needs to get changes to fs.existsSync. Would take a PR if you want to help out.

**Comment by DannyFeliz** [comment]
I have the same error
